# NumPy- Numerical Python

Works primarily with numerical data that is sorted as a multi dimensional array as a structure.



In [6]:
#Import Numpy Library

import numpy as np

In [4]:
list1= [1,2,3,4,5]

In [16]:
np.array(list1)

array([1, 2, 3, 4, 5])

Creating 2D array

In [13]:
array2d= np.array([1,2,3], [4,5,6],[7,8,9])

In [17]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
list1= [1,2,3,4]
list2= [6,7,8,9]

In [19]:
array2d= np.array([list1, list2])

In [21]:
array2d

array([[ 1,  2,  3, 45],
       [ 6,  7,  8,  9]])

#### Creating a 5 row by 3 column array that contains only the value 7

In [2]:
np.full((5,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

#### Creating a 3 row by 4 column array that contains evenly spaced values between 0-100

In [6]:
np.linspace(0,100,num=12).reshape(3,4)

array([[  0.        ,   9.09090909,  18.18181818,  27.27272727],
       [ 36.36363636,  45.45454545,  54.54545455,  63.63636364],
       [ 72.72727273,  81.81818182,  90.90909091, 100.        ]])

#### Transpose- reverse the order of axes

Transforming the rows into coluns in increment order

In [7]:
np.linspace(0,100,num=12).reshape(3,4).transpose()

array([[  0.        ,  36.36363636,  72.72727273],
       [  9.09090909,  45.45454545,  81.81818182],
       [ 18.18181818,  54.54545455,  90.90909091],
       [ 27.27272727,  63.63636364, 100.        ]])

#### Slicing -  [Start : Stp : Step]

From the 2D array stored in the variable "a" below use slicing to return the below segment



In [11]:
# Run this cell first
a = np.linspace(0,24,num=25).reshape(5,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [13]:
# here is then scling:

a[2:4,1:4]

array([[11., 12., 13.],
       [16., 17., 18.]])

Reverse the list

In [23]:
arr_1d= [2,3,4,5,6]

In [25]:
arr_1d[::-1]

[6, 5, 4, 3, 2]

Returning only elements that are greater than 12 from the same array "a" 

In [15]:
a[a>12]

array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [29]:
# Return 50 from array_2d

array_2d = np.array([[2,5,6,7,60,47,3],[11,50,6,9,62,42,30],[16,53,86,69,2,2,50]])

array_2d

In [31]:
array_2d[2,6]

50

#### Boolean Array Indexing

In [37]:
arr_1d= np.array([2,4,5,6,7])

In [38]:
arr_1d > 3     # return True when element > 3 and False if not

array([False,  True,  True,  True,  True])

In [41]:
# Return the first element

arr_1d[0]    

2

#### Concatenate

In [43]:
arr_1= np.array([[1,2,3],[4,5,6]])
arr_2= np.array([[7,8,9],[10,11,12],[13,14,15]])

In [45]:
np.concatenate((arr_1, arr_2), axis= 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

#### Numpy Sort

Sort colums and rows on asscending order


In [49]:
arr= np.array([[7,8,9],[12, 34, 54],[13,20,15]])

In [50]:
np.sort(arr, axis= 0)

array([[ 7,  8,  9],
       [12, 20, 15],
       [13, 34, 54]])

#### Arrange

In [67]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

#### NumPy Random

Created an array with randpm elements

In [71]:
np.random.rand(5,5) 

array([[0.93411248, 0.73676219, 0.49132164, 0.27120719, 0.77620409],
       [0.7149849 , 0.34253362, 0.7256017 , 0.65309301, 0.46788354],
       [0.95968851, 0.33577215, 0.70204124, 0.02593509, 0.84938975],
       [0.49239251, 0.61286766, 0.47948697, 0.60133116, 0.21647482],
       [0.67346859, 0.6493044 , 0.60279765, 0.71231588, 0.51798568]])

#### Arithmatic and Math function

In [74]:
arr_1= np.array([1,2,3])

In [77]:
(arr_1+arr_1)

array([2, 4, 6])

In [86]:
arr_1= np.array([[1,2,3], [4,5,6]])
arr_2= np.array([[7,8,9],[10,11,12]])

(arr_1+arr_2)

In [89]:
(arr_1 - arr_2)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [92]:
(arr_1 * arr_2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [94]:
(arr_1 / arr_2)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

#### SUM

In [95]:
arr_1= np.array([[1,2,3], [4,5,6]])

In [98]:
np.sum(arr_1  # Total sum of all elements

21

In [99]:
np.sum(arr_1, axis= 0)   # Sum of each column

array([5, 7, 9])

#### Mean

In [102]:
np.mean(arr_1)

3.5

#### Max

In [105]:
np.amax(arr_1)

6

#### Min

In [106]:
np.amin(arr_1)

1

#### Importing files ( csv, xlxs)

Load the file 'tfl-daily-cycle-hires-2018.csv' which i have uploaded in Git Hub repository and store it in a variable called tfl_20

In [23]:
# Load the data here

import numpy as np

tfl_20= np.loadtxt('tfl-daily-cycle-hires-2018.csv',usecols=1, skiprows=1, delimiter=',')


# This line of code reads the second column- usecols=1 from 'tfl-daily-cycle-hires-2018.csv', skipping the header- skiprows=1 row and using a comma as the separator- delimiter=','.

In [24]:
tfl_20

array([10235., 14394., 20265., 17543., 21759., 13920., 12259., 23374.,
       24683., 26787., 25222., 24696., 17512., 15070., 19161., 26921.,
       26934., 26471., 25799.,  9398.,  5859., 26337., 26003., 20206.,
       28189., 26430., 14472., 17512., 26371., 28002., 24117., 25525.,
       25331.,  8975., 13833., 23898., 25349., 25388., 25791., 21037.,
        9956., 14621., 24719., 20931., 18866., 25264., 25411., 23169.,
       18624., 19879., 25055., 26434., 26179., 23067., 16522., 14037.,
       19204., 18741., 10619.,  8744.,  8234.,  7924., 10853., 24818.,
       26301., 22044., 25967., 18912., 18717., 16259., 19996., 28069.,
       28769., 25318., 28308.,  8106.,  6624., 20488., 24582., 27719.,
       27228., 26894., 18804., 19723., 29486., 22603., 15800., 20237.,
        6362., 11032., 13504.,  7998., 22708., 23173., 30508., 30690.,
       25909.,  9759., 16324., 26751., 24883., 26473., 27363., 34235.,
       21324., 30730., 33025., 40544., 43585., 45048., 42328., 38395.,
      

Check the shape of the array

In [25]:
tfl_20.shape

(365,)

Change the array to be a 2D array of shape (365,2)


In [28]:
# Check the shape here
tfl_20= tfl_20.reshape(365,2)

In [62]:
tfl_20

array([[10235.],
       [14394.],
       [20265.],
       [17543.],
       [21759.],
       [13920.],
       [12259.],
       [23374.],
       [24683.],
       [26787.],
       [25222.],
       [24696.],
       [17512.],
       [15070.],
       [19161.],
       [26921.],
       [26934.],
       [26471.],
       [25799.],
       [ 9398.],
       [ 5859.],
       [26337.],
       [26003.],
       [20206.],
       [28189.],
       [26430.],
       [14472.],
       [17512.],
       [26371.],
       [28002.],
       [24117.],
       [25525.],
       [25331.],
       [ 8975.],
       [13833.],
       [23898.],
       [25349.],
       [25388.],
       [25791.],
       [21037.],
       [ 9956.],
       [14621.],
       [24719.],
       [20931.],
       [18866.],
       [25264.],
       [25411.],
       [23169.],
       [18624.],
       [19879.],
       [25055.],
       [26434.],
       [26179.],
       [23067.],
       [16522.],
       [14037.],
       [19204.],
       [18741.],
       [10619.

In [ ]:
Load another file 'tfl-daily-cycle-hires-2019.csv' which i have uploaded in Git Hub repository and store it in a variable called tfl_21

In [32]:
# Load the data here
tfl_21=np.loadtxt('tfl-daily-cycle-hires-2019.csv',usecols=1, skiprows=1, delimiter=',')

In [33]:
tfl_21

array([14148., 19746., 21552., 20863., 13907., 14262., 25668., 27757.,
       26568., 26022., 26378., 16750., 16304., 28097., 29413., 24500.,
       26053., 25525., 16653., 16803., 26567., 23083., 25406., 24357.,
       24198., 15062., 10596., 25859., 24732., 25482., 23487., 12841.,
       14136., 14637., 18254., 25682., 26197., 26703., 17468., 17439.,
       10800., 27439., 28786., 29145., 29270., 28838., 20560., 24383.,
       23815., 28927., 28971., 30474., 29703., 29242., 26092., 31480.,
       34996., 35420., 27219., 28255., 22795.,  9641., 26532., 29701.,
       25449., 24884., 23635., 19951., 12111., 27725., 21718., 26816.,
       23699., 26123., 14594., 14390., 27824., 27683., 30485., 31307.,
       28229., 25897., 27408., 31215., 31955., 31263., 32315., 35321.,
       33026., 20325., 31834., 24529., 27059., 25493., 27536., 20423.,
       16897., 26527., 25534., 31699., 30961., 27403., 19856., 20896.,
       30837., 31842., 37203., 36574., 36505., 38712., 36686., 35435.,
      

In [43]:
# change the shape
tfl_21= tfl_21.reshape(365,2)

In [49]:
tfl_21

array([[14148.],
       [19746.],
       [21552.],
       [20863.],
       [13907.],
       [14262.],
       [25668.],
       [27757.],
       [26568.],
       [26022.],
       [26378.],
       [16750.],
       [16304.],
       [28097.],
       [29413.],
       [24500.],
       [26053.],
       [25525.],
       [16653.],
       [16803.],
       [26567.],
       [23083.],
       [25406.],
       [24357.],
       [24198.],
       [15062.],
       [10596.],
       [25859.],
       [24732.],
       [25482.],
       [23487.],
       [12841.],
       [14136.],
       [14637.],
       [18254.],
       [25682.],
       [26197.],
       [26703.],
       [17468.],
       [17439.],
       [10800.],
       [27439.],
       [28786.],
       [29145.],
       [29270.],
       [28838.],
       [20560.],
       [24383.],
       [23815.],
       [28927.],
       [28971.],
       [30474.],
       [29703.],
       [29242.],
       [26092.],
       [31480.],
       [34996.],
       [35420.],
       [27219.

#### Concatenate

Create a new array called tfl_concat that contains the two arrays tfl_20 and tfl_21 concatenated together on the 1 axis. 

In [51]:
# Concatenate the arrays here
tfl_2021=np.concatenate([tfl_20,tfl_21], axis=1)

In [59]:
tfl_2021

array([[10235.],
       [14394.],
       [20265.],
       [17543.],
       [21759.],
       [13920.],
       [12259.],
       [23374.],
       [24683.],
       [26787.],
       [25222.],
       [24696.],
       [17512.],
       [15070.],
       [19161.],
       [26921.],
       [26934.],
       [26471.],
       [25799.],
       [ 9398.],
       [ 5859.],
       [26337.],
       [26003.],
       [20206.],
       [28189.],
       [26430.],
       [14472.],
       [17512.],
       [26371.],
       [28002.],
       [24117.],
       [25525.],
       [25331.],
       [ 8975.],
       [13833.],
       [23898.],
       [25349.],
       [25388.],
       [25791.],
       [21037.],
       [ 9956.],
       [14621.],
       [24719.],
       [20931.],
       [18866.],
       [25264.],
       [25411.],
       [23169.],
       [18624.],
       [19879.],
       [25055.],
       [26434.],
       [26179.],
       [23067.],
       [16522.],
       [14037.],
       [19204.],
       [18741.],
       [10619.

In [60]:
tfl_2021.shape

(730, 1)

Now-
1.Find the sum of the columns
2.Find the average number of bike hires for both columns
3.Find the maximum number of bike hires in both columns


In [63]:
# Sum the columns here
np.sum(tfl_2021,axis=0)

array([20992495.])

In [65]:
# Find the average of the columns here
np.mean(tfl_2021,axis=0)

array([28756.84246575])

In [66]:
# Find the maximum of both columns here
np.max(tfl_2021,axis=0)

array([46084.])